require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'pacifySDK_rn' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'Kingfisher', '= 5.7.1'
  pod 'PromiseKit/CorePromise', '= 6.10.0'
  pod 'PromiseKit/UIKit', '= 6.10.0'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'Reachability', '~> 3.2'
  
  pod 'SimpleKeychain', '~> 0.7.0'
  pod 'CocoaLumberjack/Swift', '= 3.5.3'
  pod 'zipzap', '~> 8.1.1'
  pod 'DeviceKit', '~> 1.11.0'

  pod 'EDStarRating', '~> 1.1'
  pod 'UITextView+Placeholder', '~> 1.3.3'
  pod 'AWSMobileAnalytics', '= 2.10.3'
  pod 'AFNetworking', '~> 3.2.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
#  pod 'PacifySDK', :podspec => './PacifySDK/PacifySDK.podspec'

  
  target 'pacifySDK_rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'pacifySDK_rn-tvOS' do
  # Pods for pacifySDK_rn-tvOS

  target 'pacifySDK_rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
