require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
use_frameworks!
swift_version = "5.1"

target 'pacifySDK_rn' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'PacifySDK', '= 1.0.9'
  pod 'TwilioVideo', '= 1.3.6'

  target 'pacifySDK_rnTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'pacifySDK_rn-tvOS' do
  # Pods for pacifySDK_rn-tvOS

  target 'pacifySDK_rn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
